name: ArtmapBrushes
version: 1.2 Release
main: com.dekatater.artmapbrushes.ArtmapBrushes
author: Dekatater
api-version: 1.21
depend: [NBTAPI]
description: Custom brush textures for Artmap
commands:
  artmapbrushesreload:
    description: Reloads the ArtmapBrushes configuration
    usage: /artmapbrushesreload
    permission: artmapbrushes.op
  artmapbrushespause:
    description: Pauses NBT tag application
    usage: /artmapbrushespause
    permission: artmapbrushes.op
  artmapbrushesresume:
    description: Resumes NBT tag application
    usage: /artmapbrushesresume
    permission: artmapbrushes.op
  artmapbrushesupdate:
    description: Check for plugin updates
    usage: /artmapbrushesupdate
    permission: artmapbrushes.admin
permissions:
  artmapbrushes.op:
    description: Allows usage of administrative commands (reload, pause, resume)
    default: op
  artmapbrushes.reload:
    description: Allows reloading the ArtmapBrushes config
    default: op
  artmapbrushes.admin:
    description: Allows access to admin features including update checking
    default: op