name: ArtmapBrushes
version: 1.1.0
main: com.dekatater.artmapbrushes.ArtmapBrushes
author: Dekatater
api-version: 1.21
depend: [NBTAPI]
description: Custom brush textures for Artmap
commands:
  artmapbrushesreload:
    description: Reloads the ArtmapBrushes configuration
    usage: /artmapbrushesreload
    permission: artmapbrushes.reload
permissions:
  artmapbrushes.reload:
    description: Allows reloading the ArtmapBrushes config
    default: op